name: Playwright Tests & Allure Report
run-name: ${{ github.actor }} is running the test and creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'

permissions: write-all

jobs:
  autotests:
    name: Run tests and generate Allure Report 
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
#SETUP
      - name: Clone repository
        uses: actions/checkout@v4.2.0

      - name: Set up Node 20
        uses: actions/setup-node@v4.0.4
        with:
          # node-version: 20
          node-version: lts/*
          cache: npm

      - name: Install npm
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

#Test
      # - run: npm test
      #   continue-on-error: true
      - name: Run Playwright tests
        # run: npx playwright test
        run: npm run test-allure

#Result (REPORT)
      - name: Setup Allure History
        uses: actions/checkout@v4.2.0
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        id: allure_report
        with:
          # allure_results: ./out/allure-results
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history